<?php

namespace Database\Seeders;

use App\Models\OrientationTest;
use App\Models\TestQuestion;
use Illuminate\Database\Seeder;

class OrientationTestSeeder extends Seeder
{
    public function run(): void
    {
        $tests = [

            // ─────────────────────────────────────────────────────────────────
            // TEST 1 — Aptitude & Interest Assessment
            // ─────────────────────────────────────────────────────────────────
            [
                'title'          => 'Aptitude & Interest Assessment',
                'title_fr'       => 'Évaluation des aptitudes et des intérêts',
                'title_ar'       => 'تقييم القدرات والاهتمامات',
                'description'    => 'Discover your natural strengths, cognitive aptitudes, and work preferences to identify careers that align with your abilities.',
                'description_fr' => 'Découvrez vos points forts naturels, vos aptitudes cognitives et vos préférences professionnelles pour identifier les carrières qui correspondent à vos capacités.',
                'description_ar' => 'اكتشف نقاط قوتك الطبيعية وقدراتك المعرفية وتفضيلاتك المهنية لتحديد المسارات التي تتناسب مع إمكاناتك.',
                'category'       => 'aptitude',
                'duration'    => 15,
                'status'      => 'active',
                'questions'   => [
                    [
                        'question'    => 'Which type of activity do you enjoy the most?',
                        'question_fr' => 'Quel type d\'activité appréciez-vous le plus ?',
                        'question_ar' => 'ما نوع النشاط الذي تستمتع به أكثر؟',
                        'type'        => 'single_choice',
                        'options'     => ['Building and creating things with my hands', 'Analyzing data and solving complex problems', 'Helping, teaching, or caring for others', 'Creating art, music, or writing'],
                        'options_fr'  => ['Construire et créer des choses avec mes mains', 'Analyser des données et résoudre des problèmes complexes', 'Aider, enseigner ou prendre soin des autres', 'Créer de l\'art, de la musique ou de l\'écriture'],
                        'options_ar'  => ['بناء وإنشاء الأشياء بيدي', 'تحليل البيانات وحل المشكلات المعقدة', 'مساعدة الآخرين أو تعليمهم أو الاهتمام بهم', 'إنشاء الفن أو الموسيقى أو الكتابة'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'In school, which subject comes most naturally to you?',
                        'question_fr' => 'À l\'école, quelle matière vous vient le plus naturellement ?',
                        'question_ar' => 'في المدرسة، ما المادة التي تأتيك بشكل طبيعي أكثر؟',
                        'type'        => 'single_choice',
                        'options'     => ['Mathematics and logic', 'Sciences (physics, chemistry, biology)', 'Languages and literature', 'Social sciences and humanities'],
                        'options_fr'  => ['Mathématiques et logique', 'Sciences (physique, chimie, biologie)', 'Langues et littérature', 'Sciences sociales et humanités'],
                        'options_ar'  => ['الرياضيات والمنطق', 'العلوم (فيزياء، كيمياء، أحياء)', 'اللغات والأدب', 'العلوم الاجتماعية والإنسانية'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you prefer to work?',
                        'question_fr' => 'Comment préférez-vous travailler ?',
                        'question_ar' => 'كيف تفضل العمل؟',
                        'type'        => 'single_choice',
                        'options'     => ['Independently with full autonomy', 'In a small focused team', 'Leading and guiding a group', 'Collaborating with many diverse people'],
                        'options_fr'  => ['De manière indépendante avec pleine autonomie', 'Dans une petite équipe concentrée', 'En dirigeant et guidant un groupe', 'En collaborant avec beaucoup de personnes diverses'],
                        'options_ar'  => ['باستقلالية تامة', 'في فريق صغير ومركّز', 'بقيادة وتوجيه مجموعة', 'بالتعاون مع أشخاص متنوعين'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'What matters most to you in a future career?',
                        'question_fr' => 'Qu\'est-ce qui compte le plus pour vous dans une future carrière ?',
                        'question_ar' => 'ما الأهم بالنسبة لك في مسيرتك المهنية المستقبلية؟',
                        'type'        => 'single_choice',
                        'options'     => ['Financial stability and high salary', 'Work-life balance and flexibility', 'Making a positive impact on society', 'Creative freedom and self-expression'],
                        'options_fr'  => ['Stabilité financière et salaire élevé', 'Équilibre travail-vie et flexibilité', 'Avoir un impact positif sur la société', 'Liberté créative et expression de soi'],
                        'options_ar'  => ['الاستقرار المالي والراتب المرتفع', 'التوازن بين العمل والحياة والمرونة', 'إحداث أثر إيجابي في المجتمع', 'الحرية الإبداعية والتعبير عن الذات'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'When faced with a difficult problem, what is your instinct?',
                        'question_fr' => 'Face à un problème difficile, quel est votre instinct ?',
                        'question_ar' => 'عند مواجهة مشكلة صعبة، ما هو تصرفك الفطري؟',
                        'type'        => 'single_choice',
                        'options'     => ['Research it systematically and gather data', 'Brainstorm creative solutions and experiment', 'Discuss it with others and seek advice', 'Break it into steps and work methodically'],
                        'options_fr'  => ['Faire des recherches systématiques et collecter des données', 'Chercher des solutions créatives et expérimenter', 'En discuter avec d\'autres et chercher des conseils', 'Le décomposer en étapes et travailler méthodiquement'],
                        'options_ar'  => ['البحث بشكل منهجي وجمع البيانات', 'التفكير الإبداعي والتجريب', 'مناقشته مع الآخرين وطلب النصيحة', 'تقسيمه إلى خطوات والعمل بشكل منهجي'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'Which work environment appeals to you most?',
                        'question_fr' => 'Quel environnement de travail vous attire le plus ?',
                        'question_ar' => 'ما بيئة العمل التي تناسبك أكثر؟',
                        'type'        => 'single_choice',
                        'options'     => ['Office or corporate environment', 'Laboratory or research facility', 'Outdoors or fieldwork', 'Remote or digital workspace'],
                        'options_fr'  => ['Bureau ou environnement d\'entreprise', 'Laboratoire ou centre de recherche', 'Extérieur ou travail sur le terrain', 'Espace de travail à distance ou numérique'],
                        'options_ar'  => ['بيئة مكتبية أو شركة', 'مختبر أو مرفق بحثي', 'العمل الميداني أو في الهواء الطلق', 'بيئة عمل عن بُعد أو رقمية'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How would you describe your relationship with technology?',
                        'question_fr' => 'Comment décririez-vous votre relation avec la technologie ?',
                        'question_ar' => 'كيف تصف علاقتك بالتكنولوجيا؟',
                        'type'        => 'single_choice',
                        'options'     => ['I love technology and enjoy learning new tools', 'I use technology practically to achieve goals', 'I prefer working with people over machines', 'I appreciate technology but prefer hands-on work'],
                        'options_fr'  => ['J\'adore la technologie et j\'aime apprendre de nouveaux outils', 'J\'utilise la technologie de façon pratique pour atteindre mes objectifs', 'Je préfère travailler avec des personnes plutôt qu\'avec des machines', 'J\'apprécie la technologie mais je préfère le travail manuel'],
                        'options_ar'  => ['أحب التكنولوجيا وأستمتع بتعلم أدوات جديدة', 'أستخدم التكنولوجيا بشكل عملي لتحقيق الأهداف', 'أفضل العمل مع الناس على الآلات', 'أقدّر التكنولوجيا لكنني أفضل العمل العملي'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'What kind of challenges motivate you the most?',
                        'question_fr' => 'Quel type de défis vous motive le plus ?',
                        'question_ar' => 'ما نوع التحديات التي تحفزك أكثر؟',
                        'type'        => 'single_choice',
                        'options'     => ['Technical challenges that require deep expertise', 'Social challenges involving human relationships', 'Business challenges around growth and strategy', 'Creative challenges that push artistic boundaries'],
                        'options_fr'  => ['Défis techniques nécessitant une expertise approfondie', 'Défis sociaux impliquant des relations humaines', 'Défis commerciaux autour de la croissance et de la stratégie', 'Défis créatifs qui repoussent les limites artistiques'],
                        'options_ar'  => ['تحديات تقنية تتطلب خبرة عميقة', 'تحديات اجتماعية تتعلق بالعلاقات الإنسانية', 'تحديات تجارية حول النمو والاستراتيجية', 'تحديات إبداعية تتجاوز الحدود الفنية'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you prefer to learn new things?',
                        'question_fr' => 'Comment préférez-vous apprendre de nouvelles choses ?',
                        'question_ar' => 'كيف تفضل تعلم أشياء جديدة؟',
                        'type'        => 'single_choice',
                        'options'     => ['Structured courses and formal education', 'Hands-on practice and experimentation', 'Reading books and independent research', 'Learning from mentors and through discussion'],
                        'options_fr'  => ['Cours structurés et éducation formelle', 'Pratique concrète et expérimentation', 'Lecture de livres et recherche indépendante', 'Apprendre auprès de mentors et par la discussion'],
                        'options_ar'  => ['دورات منظمة وتعليم رسمي', 'التطبيق العملي والتجريب', 'قراءة الكتب والبحث المستقل', 'التعلم من المرشدين والنقاشات'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'In 10 years, how do you picture your ideal workday?',
                        'question_fr' => 'Dans 10 ans, comment imaginez-vous votre journée de travail idéale ?',
                        'question_ar' => 'بعد 10 سنوات، كيف تتخيل يوم عملك المثالي؟',
                        'type'        => 'single_choice',
                        'options'     => ['Solving technical problems and building systems', 'Meeting clients and building relationships', 'Conducting experiments or analyzing research data', 'Creating content, designs, or artistic work'],
                        'options_fr'  => ['Résoudre des problèmes techniques et construire des systèmes', 'Rencontrer des clients et établir des relations', 'Mener des expériences ou analyser des données de recherche', 'Créer du contenu, des designs ou des œuvres artistiques'],
                        'options_ar'  => ['حل المشكلات التقنية وبناء الأنظمة', 'مقابلة العملاء وبناء العلاقات', 'إجراء التجارب أو تحليل بيانات البحث', 'إنشاء المحتوى أو التصاميم أو الأعمال الفنية'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'Which describes your decision-making style?',
                        'question_fr' => 'Quelle description correspond à votre style de prise de décision ?',
                        'question_ar' => 'ما الذي يصف أسلوبك في اتخاذ القرارات؟',
                        'type'        => 'single_choice',
                        'options'     => ['Data-driven — I rely on facts and numbers', 'Intuition-driven — I trust my gut feeling', 'People-driven — I consider how others are affected', 'Process-driven — I follow established frameworks'],
                        'options_fr'  => ['Basé sur les données — je m\'appuie sur les faits et les chiffres', 'Basé sur l\'intuition — je fais confiance à mon instinct', 'Basé sur les personnes — je considère comment les autres sont affectés', 'Basé sur les processus — je suis des cadres établis'],
                        'options_ar'  => ['مدفوع بالبيانات — أعتمد على الحقائق والأرقام', 'مدفوع بالحدس — أثق بحدسي', 'مدفوع بالناس — أراعي تأثير القرارات على الآخرين', 'مدفوع بالعمليات — أتبع الأطر المحددة'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you feel about repetitive, routine tasks?',
                        'question_fr' => 'Que pensez-vous des tâches répétitives et routinières ?',
                        'question_ar' => 'كيف تشعر تجاه المهام المتكررة والروتينية؟',
                        'type'        => 'single_choice',
                        'options'     => ['I find comfort in routine and structure', 'I tolerate routine if the work is meaningful', 'I prefer variety and new challenges daily', 'I actively seek roles with constant change'],
                        'options_fr'  => ['Je trouve du réconfort dans la routine et la structure', 'Je tolère la routine si le travail est significatif', 'Je préfère la variété et de nouveaux défis quotidiens', 'Je recherche activement des rôles avec un changement constant'],
                        'options_ar'  => ['أجد الراحة في الروتين والهيكل', 'أتحمل الروتين إذا كان العمل ذا معنى', 'أفضل التنوع والتحديات الجديدة يومياً', 'أبحث بنشاط عن أدوار تتميز بالتغيير المستمر'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'What role does money play in your career choice?',
                        'question_fr' => 'Quel rôle joue l\'argent dans votre choix de carrière ?',
                        'question_ar' => 'ما دور المال في اختيارك للمهنة؟',
                        'type'        => 'single_choice',
                        'options'     => ['It is my primary motivator', 'It is important but not the only factor', 'It matters less than passion and purpose', 'I prioritize stability over high income'],
                        'options_fr'  => ['C\'est ma principale motivation', 'C\'est important mais pas le seul facteur', 'Cela compte moins que la passion et le but', 'Je privilégie la stabilité plutôt qu\'un revenu élevé'],
                        'options_ar'  => ['هو دافعي الأساسي', 'مهم لكنه ليس العامل الوحيد', 'يهمني أقل من الشغف والهدف', 'أولوية الاستقرار على الدخل المرتفع'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you feel about leading or managing others?',
                        'question_fr' => 'Que ressentez-vous à l\'idée de diriger ou gérer d\'autres personnes ?',
                        'question_ar' => 'كيف تشعر تجاه قيادة الآخرين أو إدارتهم؟',
                        'type'        => 'single_choice',
                        'options'     => ['I naturally take charge and enjoy leadership', 'I lead when needed but prefer collaboration', 'I prefer to contribute as an individual', 'I actively avoid management responsibilities'],
                        'options_fr'  => ['Je prends naturellement les commandes et j\'aime diriger', 'Je dirige quand c\'est nécessaire mais préfère la collaboration', 'Je préfère contribuer en tant qu\'individu', 'J\'évite activement les responsabilités de gestion'],
                        'options_ar'  => ['أتولى القيادة بشكل طبيعي وأستمتع بها', 'أقود عند الحاجة لكنني أفضل التعاون', 'أفضل المساهمة كفرد', 'أتجنب بنشاط مسؤوليات الإدارة'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'Which of these would you most enjoy spending a full day doing?',
                        'question_fr' => 'Lequel de ces activités apprécierez-vous le plus passer une journée entière à faire ?',
                        'question_ar' => 'أيٌّ من هذه الأنشطة ستستمتع بقضاء يوم كامل فيه؟',
                        'type'        => 'single_choice',
                        'options'     => ['Writing code or designing a digital product', 'Diagnosing and treating a patient', 'Planning and executing a business strategy', 'Drawing, filming, or producing creative work'],
                        'options_fr'  => ['Écrire du code ou concevoir un produit numérique', 'Diagnostiquer et traiter un patient', 'Planifier et exécuter une stratégie commerciale', 'Dessiner, filmer ou produire un travail créatif'],
                        'options_ar'  => ['كتابة الكود أو تصميم منتج رقمي', 'تشخيص المريض وعلاجه', 'التخطيط وتنفيذ استراتيجية تجارية', 'الرسم أو التصوير أو إنتاج عمل إبداعي'],
                        'points'      => 10,
                    ],
                ],
            ],

            // ─────────────────────────────────────────────────────────────────
            // TEST 2 — Values & Personality Profile
            // ─────────────────────────────────────────────────────────────────
            [
                'title'          => 'Values & Personality Profile',
                'title_fr'       => 'Profil de valeurs et de personnalité',
                'title_ar'       => 'ملف القيم والشخصية',
                'description'    => 'Understand your core values, personality traits, and motivational drivers to find your ideal career fit.',
                'description_fr' => 'Comprenez vos valeurs fondamentales, vos traits de personnalité et vos motivations pour trouver la carrière idéale.',
                'description_ar' => 'افهم قيمك الأساسية وسمات شخصيتك ومحركاتك التحفيزية للعثور على المسار المهني المثالي لك.',
                'category'       => 'personality',
                'duration'    => 15,
                'status'      => 'active',
                'questions'   => [
                    [
                        'question'    => 'Which value is most important to you in life?',
                        'question_fr' => 'Quelle valeur est la plus importante pour vous dans la vie ?',
                        'question_ar' => 'ما القيمة الأهم بالنسبة لك في الحياة؟',
                        'type'        => 'single_choice',
                        'options'     => ['Achievement and excellence', 'Security and stability', 'Adventure and exploration', 'Service and contribution to others'],
                        'options_fr'  => ['Accomplissement et excellence', 'Sécurité et stabilité', 'Aventure et exploration', 'Service et contribution aux autres'],
                        'options_ar'  => ['الإنجاز والتميز', 'الأمان والاستقرار', 'المغامرة والاستكشاف', 'الخدمة والمساهمة للآخرين'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you typically handle stress?',
                        'question_fr' => 'Comment gérez-vous généralement le stress ?',
                        'question_ar' => 'كيف تتعامل عادةً مع الضغط والتوتر؟',
                        'type'        => 'single_choice',
                        'options'     => ['Stay calm and think logically', 'Seek support from friends or family', 'Channel it into creative work', 'Exercise and take physical action'],
                        'options_fr'  => ['Rester calme et penser logiquement', 'Chercher le soutien d\'amis ou de la famille', 'Le canaliser dans un travail créatif', 'Faire de l\'exercice et agir physiquement'],
                        'options_ar'  => ['أبقى هادئاً وأفكر بمنطق', 'أطلب الدعم من الأصدقاء أو العائلة', 'أوجهه نحو عمل إبداعي', 'أمارس الرياضة وأتخذ إجراءات جسدية'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'Which statement best describes you?',
                        'question_fr' => 'Quelle affirmation vous décrit le mieux ?',
                        'question_ar' => 'ما العبارة التي تصفك أكثر؟',
                        'type'        => 'single_choice',
                        'options'     => ['I am detail-oriented and precise', 'I am a big-picture thinker and strategist', 'I am empathetic and people-focused', 'I am creative and always thinking of new ideas'],
                        'options_fr'  => ['Je suis orienté vers les détails et précis', 'Je suis un penseur global et stratège', 'Je suis empathique et centré sur les personnes', 'Je suis créatif et je pense toujours à de nouvelles idées'],
                        'options_ar'  => ['أنا منتبه للتفاصيل ودقيق', 'أنا مفكر استراتيجي يرى الصورة الكبيرة', 'أنا متعاطف ومتمحور حول الناس', 'أنا مبدع ودائم التفكير في أفكار جديدة'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you feel about taking risks?',
                        'question_fr' => 'Que pensez-vous de la prise de risques ?',
                        'question_ar' => 'كيف تشعر تجاه المخاطرة؟',
                        'type'        => 'single_choice',
                        'options'     => ['I avoid risks and prefer certainty', 'I take calculated risks with careful planning', 'I embrace risks as opportunities for growth', 'I prefer small risks within a safe framework'],
                        'options_fr'  => ['J\'évite les risques et préfère la certitude', 'Je prends des risques calculés avec une planification soigneuse', 'J\'accepte les risques comme des opportunités de croissance', 'Je préfère les petits risques dans un cadre sécurisé'],
                        'options_ar'  => ['أتجنب المخاطر وأفضل اليقين', 'أتخذ مخاطر محسوبة بتخطيط دقيق', 'أتقبل المخاطر كفرص للنمو', 'أفضل المخاطر الصغيرة ضمن إطار آمن'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'When working on a group project, you naturally take on which role?',
                        'question_fr' => 'Lors d\'un projet de groupe, quel rôle prenez-vous naturellement ?',
                        'question_ar' => 'عند العمل على مشروع جماعي، ما الدور الذي تأخذه بشكل طبيعي؟',
                        'type'        => 'single_choice',
                        'options'     => ['The organizer who structures everything', 'The idea generator who proposes solutions', 'The peacemaker who ensures harmony', 'The executor who gets things done'],
                        'options_fr'  => ['L\'organisateur qui structure tout', 'Le générateur d\'idées qui propose des solutions', 'Le pacificateur qui assure l\'harmonie', 'L\'exécutant qui fait avancer les choses'],
                        'options_ar'  => ['المنظم الذي يهيكل كل شيء', 'مولّد الأفكار الذي يقترح الحلول', 'صانع السلام الذي يضمن الانسجام', 'المنفذ الذي ينجز الأمور'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'Which describes your ideal impact on the world?',
                        'question_fr' => 'Quelle description correspond à l\'impact idéal que vous souhaitez avoir sur le monde ?',
                        'question_ar' => 'ما الأثر المثالي الذي تريد إحداثه في العالم؟',
                        'type'        => 'single_choice',
                        'options'     => ['Build innovative technology that changes how people live', 'Heal people and improve public health', 'Create economic opportunity and employment', 'Advance knowledge through science and research'],
                        'options_fr'  => ['Construire une technologie innovante qui change la façon dont les gens vivent', 'Soigner les gens et améliorer la santé publique', 'Créer des opportunités économiques et de l\'emploi', 'Faire avancer la connaissance grâce à la science et à la recherche'],
                        'options_ar'  => ['بناء تكنولوجيا مبتكرة تغير حياة الناس', 'علاج الناس وتحسين الصحة العامة', 'خلق فرص اقتصادية وتوظيف', 'تطوير المعرفة من خلال العلم والبحث'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you feel about long-term study (5+ years at university)?',
                        'question_fr' => 'Que pensez-vous des études à long terme (5 ans ou plus à l\'université) ?',
                        'question_ar' => 'كيف تشعر تجاه الدراسة الطويلة (5 سنوات أو أكثر في الجامعة)؟',
                        'type'        => 'single_choice',
                        'options'     => ['Excited – I love learning and academic environments', 'Open – if it leads to a rewarding career', 'Neutral – I prefer shorter, more practical programs', 'Reluctant – I prefer entering the workforce sooner'],
                        'options_fr'  => ['Enthousiaste – j\'adore apprendre et les environnements académiques', 'Ouvert – si cela mène à une carrière enrichissante', 'Neutre – je préfère des programmes plus courts et pratiques', 'Réticent – je préfère intégrer le marché du travail plus tôt'],
                        'options_ar'  => ['متحمس — أحب التعلم والبيئات الأكاديمية', 'منفتح — إذا أدى إلى مسيرة مهنية مجزية', 'محايد — أفضل البرامج الأقصر والأكثر عملية', 'متردد — أفضل الدخول لسوق العمل مبكراً'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'What do people most often ask for your help with?',
                        'question_fr' => 'Pour quoi les gens vous demandent-ils le plus souvent de l\'aide ?',
                        'question_ar' => 'بماذا يطلب منك الناس المساعدة في أغلب الأحيان؟',
                        'type'        => 'single_choice',
                        'options'     => ['Technical problems (computers, devices, math)', 'Personal advice and emotional support', 'Creative projects (design, writing, ideas)', 'Planning and organizing tasks or events'],
                        'options_fr'  => ['Problèmes techniques (ordinateurs, appareils, mathématiques)', 'Conseils personnels et soutien émotionnel', 'Projets créatifs (design, écriture, idées)', 'Planification et organisation de tâches ou d\'événements'],
                        'options_ar'  => ['مشكلات تقنية (حاسوب، أجهزة، رياضيات)', 'نصائح شخصية ودعم عاطفي', 'مشاريع إبداعية (تصميم، كتابة، أفكار)', 'تخطيط وتنظيم المهام أو الفعاليات'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'Which achievement would make you most proud?',
                        'question_fr' => 'Quelle réalisation vous rendrait le plus fier ?',
                        'question_ar' => 'أي إنجاز سيجعلك أكثر فخراً؟',
                        'type'        => 'single_choice',
                        'options'     => ['Building a successful product or company', 'Publishing research that advances human knowledge', 'Helping thousands of people improve their lives', 'Creating art or work that inspires others'],
                        'options_fr'  => ['Construire un produit ou une entreprise prospère', 'Publier des recherches qui font avancer la connaissance humaine', 'Aider des milliers de personnes à améliorer leur vie', 'Créer de l\'art ou un travail qui inspire les autres'],
                        'options_ar'  => ['بناء منتج أو شركة ناجحة', 'نشر بحث يطور المعرفة الإنسانية', 'مساعدة الآلاف على تحسين حياتهم', 'إنشاء فن أو عمل يلهم الآخرين'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => "How do you feel about Morocco's growing tech and business sectors?",
                        'question_fr' => 'Que pensez-vous des secteurs technologiques et commerciaux en pleine croissance au Maroc ?',
                        'question_ar' => 'كيف تشعر تجاه قطاعي التقنية والأعمال المتنامين في المغرب؟',
                        'type'        => 'single_choice',
                        'options'     => ['Very excited – I want to be part of this growth', 'Interested in opportunities it creates locally', 'Prefer to work internationally and abroad', 'Focused on traditional sectors like medicine or law'],
                        'options_fr'  => ['Très enthousiaste – je veux faire partie de cette croissance', 'Intéressé par les opportunités qu\'il crée localement', 'Préférer travailler à l\'international et à l\'étranger', 'Concentré sur les secteurs traditionnels comme la médecine ou le droit'],
                        'options_ar'  => ['متحمس جداً — أريد أن أكون جزءاً من هذا النمو', 'مهتم بالفرص التي يخلقها محلياً', 'أفضل العمل دولياً وفي الخارج', 'مركّز على القطاعات التقليدية مثل الطب أو القانون'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you define personal success?',
                        'question_fr' => 'Comment définissez-vous le succès personnel ?',
                        'question_ar' => 'كيف تعرّف النجاح الشخصي؟',
                        'type'        => 'single_choice',
                        'options'     => ['Wealth and financial independence', 'Recognition and professional status', 'Personal fulfillment and happiness', 'Positive contribution to my community'],
                        'options_fr'  => ['Richesse et indépendance financière', 'Reconnaissance et statut professionnel', 'Épanouissement personnel et bonheur', 'Contribution positive à ma communauté'],
                        'options_ar'  => ['الثروة والاستقلال المالي', 'التقدير والمكانة المهنية', 'الإشباع الشخصي والسعادة', 'المساهمة الإيجابية في مجتمعي'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you feel about working across different cultures or internationally?',
                        'question_fr' => 'Que ressentez-vous à l\'idée de travailler dans différentes cultures ou à l\'international ?',
                        'question_ar' => 'كيف تشعر تجاه العمل مع ثقافات مختلفة أو على المستوى الدولي؟',
                        'type'        => 'single_choice',
                        'options'     => ['I love it — diversity energizes me', 'I am open to it with the right preparation', 'I prefer a familiar local environment', 'It depends on the opportunity'],
                        'options_fr'  => ['J\'adore ça — la diversité m\'energise', 'Je suis ouvert avec la bonne préparation', 'Je préfère un environnement local familier', 'Cela dépend de l\'opportunité'],
                        'options_ar'  => ['أحبه — التنوع يعطيني طاقة', 'أنا منفتح عليه مع التحضير المناسب', 'أفضل البيئة المحلية المألوفة', 'يعتمد على الفرصة'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'What is your relationship with authority and hierarchy at work?',
                        'question_fr' => 'Quelle est votre relation avec l\'autorité et la hiérarchie au travail ?',
                        'question_ar' => 'ما علاقتك بالسلطة والتسلسل الهرمي في العمل؟',
                        'type'        => 'single_choice',
                        'options'     => ['I respect structure and follow it well', 'I work within it but prefer flat teams', 'I question it and prefer open dialogue', 'I want to be the one setting the direction'],
                        'options_fr'  => ['Je respecte la structure et la suis bien', 'Je travaille dans ce cadre mais préfère des équipes plates', 'Je la remets en question et préfère un dialogue ouvert', 'Je veux être celui qui fixe la direction'],
                        'options_ar'  => ['أحترم الهيكل وأتبعه جيداً', 'أعمل ضمنه لكنني أفضل الفرق المسطحة', 'أشكك فيه وأفضل الحوار المفتوح', 'أريد أن أكون من يحدد التوجه'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'Which of these describes your social energy?',
                        'question_fr' => 'Laquelle de ces descriptions correspond à votre énergie sociale ?',
                        'question_ar' => 'أيٌّ من هذه العبارات يصف طاقتك الاجتماعية؟',
                        'type'        => 'single_choice',
                        'options'     => ['Extrovert — energized by people and interaction', 'Ambivert — depends on the situation', 'Introvert — I recharge through alone time', 'Highly social only in professional settings'],
                        'options_fr'  => ['Extraverti — énergisé par les personnes et les interactions', 'Ambivert — dépend de la situation', 'Introverti — je me ressource par la solitude', 'Très sociable uniquement dans des contextes professionnels'],
                        'options_ar'  => ['انبساطي — أستمد طاقتي من الناس والتفاعل', 'متوسط — يعتمد على الموقف', 'انطوائي — أجدد طاقتي بالوقت مع نفسي', 'اجتماعي للغاية فقط في البيئات المهنية'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'When you imagine yourself at 35, what does your life look like?',
                        'question_fr' => 'Lorsque vous vous imaginez à 35 ans, à quoi ressemble votre vie ?',
                        'question_ar' => 'عندما تتخيل نفسك في سن 35، كيف تبدو حياتك؟',
                        'type'        => 'single_choice',
                        'options'     => ['Running my own business or startup', 'Leading a team in a major company', 'Practicing a respected profession (doctor, lawyer, engineer)', 'Working freely as a creator or consultant'],
                        'options_fr'  => ['Diriger ma propre entreprise ou startup', 'Diriger une équipe dans une grande entreprise', 'Exercer une profession respectée (médecin, avocat, ingénieur)', 'Travailler librement en tant que créateur ou consultant'],
                        'options_ar'  => ['إدارة عملي الخاص أو شركة ناشئة', 'قيادة فريق في شركة كبرى', 'ممارسة مهنة محترمة (طبيب، محامي، مهندس)', 'العمل بحرية كمبدع أو مستشار'],
                        'points'      => 10,
                    ],
                ],
            ],

            // ─────────────────────────────────────────────────────────────────
            // TEST 3 — Skills & Academic Strength Test
            // ─────────────────────────────────────────────────────────────────
            [
                'title'          => 'Skills & Academic Strength Test',
                'title_fr'       => 'Test de compétences et de forces académiques',
                'title_ar'       => 'اختبار المهارات والقدرات الأكاديمية',
                'description'    => 'Assess your academic strengths, practical skills, and learning style to match you with programs that suit your abilities.',
                'description_fr' => 'Évaluez vos points forts académiques, vos compétences pratiques et votre style d\'apprentissage pour vous orienter vers les programmes qui vous conviennent.',
                'description_ar' => 'قيّم نقاط قوتك الأكاديمية ومهاراتك العملية وأسلوب تعلمك لمطابقتك مع البرامج التي تناسب قدراتك.',
                'category'       => 'skills',
                'duration'    => 15,
                'status'      => 'active',
                'questions'   => [
                    [
                        'question'    => 'How confident are you in mathematics and quantitative reasoning?',
                        'question_fr' => 'Quelle est votre confiance en mathématiques et en raisonnement quantitatif ?',
                        'question_ar' => 'ما مدى ثقتك في الرياضيات والتفكير الكمي؟',
                        'type'        => 'single_choice',
                        'options'     => ['Very confident – it is one of my strongest subjects', 'Moderately confident – I can handle it when needed', 'Somewhat weak – I struggle but manage', 'Not confident – I prefer non-mathematical fields'],
                        'options_fr'  => ['Très confiant – c\'est l\'une de mes matières les plus solides', 'Modérément confiant – je peux m\'en sortir quand nécessaire', 'Plutôt faible – j\'ai du mal mais je gère', 'Pas confiant – je préfère les domaines non mathématiques'],
                        'options_ar'  => ['واثق جداً — إنها من أقوى موادي', 'واثق نسبياً — أستطيع التعامل معها عند الحاجة', 'ضعيف نسبياً — أجد صعوبة لكنني أتعامل معها', 'غير واثق — أفضل المجالات غير الرياضية'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How would you rate your writing and communication skills?',
                        'question_fr' => 'Comment évalueriez-vous vos compétences en rédaction et en communication ?',
                        'question_ar' => 'كيف تقيّم مهاراتك في الكتابة والتواصل؟',
                        'type'        => 'single_choice',
                        'options'     => ['Excellent – I write clearly and persuasively', 'Good – I communicate effectively in most situations', 'Average – I can get my point across', 'Developing – I find writing challenging'],
                        'options_fr'  => ['Excellent – j\'écris clairement et de manière persuasive', 'Bon – je communique efficacement dans la plupart des situations', 'Moyen – je peux faire passer mon message', 'En développement – je trouve la rédaction difficile'],
                        'options_ar'  => ['ممتاز — أكتب بوضوح وإقناع', 'جيد — أتواصل بفعالية في معظم المواقف', 'متوسط — أستطيع إيصال وجهة نظري', 'في طور التطوير — أجد الكتابة تحدياً'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you approach scientific experiments or laboratory work?',
                        'question_fr' => 'Comment abordez-vous les expériences scientifiques ou les travaux en laboratoire ?',
                        'question_ar' => 'كيف تتعامل مع التجارب العلمية أو العمل في المختبر؟',
                        'type'        => 'single_choice',
                        'options'     => ['I love it – hands-on experimentation excites me', 'I enjoy it when it connects to real applications', 'It is okay but not my favorite type of work', 'I prefer theoretical study over lab work'],
                        'options_fr'  => ['J\'adore ça – l\'expérimentation pratique m\'enthousiasme', 'J\'aime ça quand cela se connecte à des applications réelles', 'C\'est correct mais pas mon type de travail préféré', 'Je préfère l\'étude théorique au travail en laboratoire'],
                        'options_ar'  => ['أحبه — التجريب العملي يثير حماسي', 'أستمتع به عندما يرتبط بتطبيقات حقيقية', 'لا بأس به لكنه ليس نوع عملي المفضل', 'أفضل الدراسة النظرية على العمل المختبري'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'What is your level of experience with computers and programming?',
                        'question_fr' => 'Quel est votre niveau d\'expérience avec les ordinateurs et la programmation ?',
                        'question_ar' => 'ما مستوى خبرتك بالحواسيب والبرمجة؟',
                        'type'        => 'single_choice',
                        'options'     => ['Advanced – I code and build projects regularly', 'Intermediate – I understand basics and can learn quickly', 'Beginner – I use computers but do not program', 'Minimal – I prefer non-digital work'],
                        'options_fr'  => ['Avancé – je code et construis des projets régulièrement', 'Intermédiaire – je comprends les bases et peux apprendre rapidement', 'Débutant – j\'utilise des ordinateurs mais ne programme pas', 'Minimal – je préfère le travail non numérique'],
                        'options_ar'  => ['متقدم — أبرمج وأبني مشاريع بانتظام', 'متوسط — أفهم الأساسيات ويمكنني التعلم بسرعة', 'مبتدئ — أستخدم الحاسوب لكنني لا أبرمج', 'محدود — أفضل العمل غير الرقمي'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you perform under pressure and tight deadlines?',
                        'question_fr' => 'Comment performez-vous sous pression et avec des délais serrés ?',
                        'question_ar' => 'كيف تؤدي عملك تحت الضغط والمواعيد النهائية الضيقة؟',
                        'type'        => 'single_choice',
                        'options'     => ['I thrive under pressure and produce my best work', 'I manage well with good time management', 'I sometimes struggle but adapt over time', 'I prefer working without time pressure'],
                        'options_fr'  => ['Je m\'épanouis sous pression et produis mon meilleur travail', 'Je m\'en sors bien avec une bonne gestion du temps', 'J\'ai parfois du mal mais je m\'adapte avec le temps', 'Je préfère travailler sans pression de temps'],
                        'options_ar'  => ['أزدهر تحت الضغط وأنتج أفضل أعمالي', 'أتعامل معه جيداً بإدارة وقت جيدة', 'أجد صعوبة أحياناً لكنني أتكيف مع الوقت', 'أفضل العمل دون ضغط زمني'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How comfortable are you with public speaking and presentations?',
                        'question_fr' => 'À quel point êtes-vous à l\'aise avec la prise de parole en public et les présentations ?',
                        'question_ar' => 'ما مدى ارتياحك للتحدث أمام الجمهور وتقديم العروض؟',
                        'type'        => 'single_choice',
                        'options'     => ['Very comfortable – I enjoy presenting to groups', 'Comfortable with preparation', 'Nervous but I manage', 'I strongly prefer behind-the-scenes work'],
                        'options_fr'  => ['Très à l\'aise – j\'aime présenter devant des groupes', 'À l\'aise avec de la préparation', 'Nerveux mais je gère', 'Je préfère fortement le travail en coulisses'],
                        'options_ar'  => ['مرتاح جداً — أستمتع بالتحدث أمام المجموعات', 'مرتاح مع التحضير المسبق', 'متوتر لكنني أتعامل معه', 'أفضل بشدة العمل خلف الكواليس'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you handle ambiguous or open-ended problems with no clear answer?',
                        'question_fr' => 'Comment gérez-vous les problèmes ambigus ou ouverts sans réponse claire ?',
                        'question_ar' => 'كيف تتعامل مع المشكلات الغامضة أو المفتوحة التي لا إجابة واضحة لها؟',
                        'type'        => 'single_choice',
                        'options'     => ['I enjoy the freedom to explore and discover', 'I create structure to navigate ambiguity', 'I prefer more defined problems with clear solutions', 'I find them frustrating without guidance'],
                        'options_fr'  => ['J\'apprécie la liberté d\'explorer et de découvrir', 'Je crée une structure pour naviguer dans l\'ambiguïté', 'Je préfère des problèmes plus définis avec des solutions claires', 'Je les trouve frustrants sans guidance'],
                        'options_ar'  => ['أستمتع بحرية الاستكشاف والاكتشاف', 'أخلق هيكلاً للتعامل مع الغموض', 'أفضل المشكلات الأكثر تحديداً ذات الحلول الواضحة', 'أجدها محبطة دون توجيه'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'Which best describes your approach to creative tasks?',
                        'question_fr' => 'Quelle description correspond le mieux à votre approche des tâches créatives ?',
                        'question_ar' => 'ما الذي يصف نهجك في المهام الإبداعية بشكل أفضل؟',
                        'type'        => 'single_choice',
                        'options'     => ['Highly creative – I constantly generate original ideas', 'Creative when inspired or challenged', 'Practical – I prefer refining existing ideas', 'Analytical – creativity is not my primary strength'],
                        'options_fr'  => ['Très créatif – je génère constamment des idées originales', 'Créatif quand je suis inspiré ou challengé', 'Pratique – je préfère affiner les idées existantes', 'Analytique – la créativité n\'est pas ma force principale'],
                        'options_ar'  => ['إبداعي للغاية — أولّد أفكاراً أصيلة باستمرار', 'مبدع عندما أشعر بالإلهام أو التحدي', 'عملي — أفضل تحسين الأفكار الموجودة', 'تحليلي — الإبداع ليس نقطة قوتي الأساسية'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How well do you work with large amounts of data or information?',
                        'question_fr' => 'Comment travaillez-vous avec de grandes quantités de données ou d\'informations ?',
                        'question_ar' => 'كيف تتعامل مع كميات كبيرة من البيانات أو المعلومات؟',
                        'type'        => 'single_choice',
                        'options'     => ['Very well – I enjoy finding patterns in data', 'Well – I can organize and interpret data effectively', 'Average – I manage when necessary', 'I prefer qualitative work over data analysis'],
                        'options_fr'  => ['Très bien – j\'aime trouver des modèles dans les données', 'Bien – je peux organiser et interpréter les données efficacement', 'Moyen – je gère quand c\'est nécessaire', 'Je préfère le travail qualitatif à l\'analyse de données'],
                        'options_ar'  => ['جيد جداً — أستمتع بإيجاد الأنماط في البيانات', 'جيد — أستطيع تنظيم البيانات وتفسيرها بفعالية', 'متوسط — أتعامل معها عند الحاجة', 'أفضل العمل النوعي على تحليل البيانات'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How strong are your foreign language skills (e.g., French, English, Spanish)?',
                        'question_fr' => 'Quel est votre niveau en langues étrangères (ex. français, anglais, espagnol) ?',
                        'question_ar' => 'ما مستوى مهاراتك في اللغات الأجنبية (مثل الفرنسية، الإنجليزية، الإسبانية)؟',
                        'type'        => 'single_choice',
                        'options'     => ['Fluent in 2+ languages beyond Arabic and Darija', 'Proficient in one foreign language', 'Basic level in one foreign language', 'I primarily communicate in Arabic or Darija'],
                        'options_fr'  => ['Courant dans 2+ langues au-delà de l\'arabe et du darija', 'Compétent dans une langue étrangère', 'Niveau de base dans une langue étrangère', 'Je communique principalement en arabe ou en darija'],
                        'options_ar'  => ['طليق في لغتين أو أكثر بالإضافة للعربية والدارجة', 'متمكن من لغة أجنبية واحدة', 'مستوى أساسي في لغة أجنبية واحدة', 'أتواصل أساساً بالعربية أو الدارجة'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you rate your ability to research and self-learn independently?',
                        'question_fr' => 'Comment évaluez-vous votre capacité à faire des recherches et à apprendre de manière autonome ?',
                        'question_ar' => 'كيف تقيّم قدرتك على البحث والتعلم الذاتي؟',
                        'type'        => 'single_choice',
                        'options'     => ['Excellent – I regularly learn new things on my own', 'Good – I can research effectively when motivated', 'Average – I prefer guided learning environments', 'I rely heavily on teachers or structured programs'],
                        'options_fr'  => ['Excellent – j\'apprends régulièrement de nouvelles choses par moi-même', 'Bon – je peux faire des recherches efficacement quand je suis motivé', 'Moyen – je préfère les environnements d\'apprentissage guidé', 'Je dépends fortement des enseignants ou des programmes structurés'],
                        'options_ar'  => ['ممتاز — أتعلم أشياء جديدة بنفسي بانتظام', 'جيد — أستطيع البحث بفعالية عندما أكون متحفزاً', 'متوسط — أفضل بيئات التعلم الموجّه', 'أعتمد بشكل كبير على المعلمين أو البرامج المنظمة'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you feel about working with numbers in a professional context?',
                        'question_fr' => 'Que ressentez-vous à l\'idée de travailler avec des chiffres dans un contexte professionnel ?',
                        'question_ar' => 'كيف تشعر تجاه العمل بالأرقام في سياق مهني؟',
                        'type'        => 'single_choice',
                        'options'     => ['I enjoy financial modeling, budgeting, or accounting', 'I can work with numbers but prefer other tasks', 'I avoid number-heavy work when possible', 'Numbers are a major weakness for me'],
                        'options_fr'  => ['J\'aime la modélisation financière, la budgétisation ou la comptabilité', 'Je peux travailler avec des chiffres mais préfère d\'autres tâches', 'J\'évite le travail intensive en chiffres quand c\'est possible', 'Les chiffres sont une faiblesse majeure pour moi'],
                        'options_ar'  => ['أستمتع بالنمذجة المالية أو الميزانية أو المحاسبة', 'أستطيع العمل بالأرقام لكنني أفضل مهام أخرى', 'أتجنب العمل الكثيف بالأرقام عند الإمكان', 'الأرقام نقطة ضعف كبيرة بالنسبة لي'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How would you describe your organizational and planning skills?',
                        'question_fr' => 'Comment décririez-vous vos compétences en organisation et en planification ?',
                        'question_ar' => 'كيف تصف مهاراتك في التنظيم والتخطيط؟',
                        'type'        => 'single_choice',
                        'options'     => ['Highly organized – I plan everything meticulously', 'Generally organized – I meet deadlines reliably', 'Somewhat disorganized – I improve under structure', 'I struggle with long-term planning'],
                        'options_fr'  => ['Très organisé – je planifie tout méticuleusement', 'Généralement organisé – je respecte les délais de manière fiable', 'Plutôt désorganisé – je m\'améliore sous structure', 'J\'ai du mal avec la planification à long terme'],
                        'options_ar'  => ['منظم للغاية — أخطط لكل شيء بدقة', 'منظم بشكل عام — أفي بالمواعيد النهائية بموثوقية', 'غير منظم نسبياً — أتحسن ضمن الهيكل', 'أجد صعوبة في التخطيط طويل المدى'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'How do you approach learning a completely new subject from scratch?',
                        'question_fr' => 'Comment abordez-vous l\'apprentissage d\'un sujet complètement nouveau de zéro ?',
                        'question_ar' => 'كيف تتعامل مع تعلم موضوع جديد تماماً من الصفر؟',
                        'type'        => 'single_choice',
                        'options'     => ['I dive in immediately and learn as I go', 'I create a structured learning plan first', 'I look for a course or mentor to guide me', 'I find it challenging and need a lot of support'],
                        'options_fr'  => ['Je plonge immédiatement et j\'apprends en avançant', 'Je crée d\'abord un plan d\'apprentissage structuré', 'Je cherche un cours ou un mentor pour me guider', 'Je le trouve difficile et j\'ai besoin de beaucoup de soutien'],
                        'options_ar'  => ['أنغمس فيه فوراً وأتعلم أثناء التقدم', 'أنشئ خطة تعلم منظمة أولاً', 'أبحث عن دورة أو مرشد ليوجهني', 'أجده صعباً وأحتاج إلى دعم كبير'],
                        'points'      => 10,
                    ],
                    [
                        'question'    => 'Which academic track describes your background or interest best?',
                        'question_fr' => 'Quelle filière académique décrit le mieux votre parcours ou intérêt ?',
                        'question_ar' => 'ما المسار الدراسي الذي يصف خلفيتك أو اهتمامك بشكل أفضل؟',
                        'type'        => 'single_choice',
                        'options'     => ['Sciences (Maths, Physics, Chemistry, Biology)', 'Technology and Engineering (Informatique, Sciences de l\'ingénieur)', 'Economics and Management (Sciences économiques)', 'Literature and Humanities (Lettres, Sciences humaines)'],
                        'options_fr'  => ['Sciences (Maths, Physique, Chimie, Biologie)', 'Technologie et ingénierie (Informatique, Sciences de l\'ingénieur)', 'Économie et gestion (Sciences économiques)', 'Littérature et humanités (Lettres, Sciences humaines)'],
                        'options_ar'  => ['العلوم (رياضيات، فيزياء، كيمياء، أحياء)', 'التكنولوجيا والهندسة (إعلاميات، علوم المهندس)', 'الاقتصاد والتدبير (العلوم الاقتصادية)', 'الآداب والعلوم الإنسانية (آداب، علوم إنسانية)'],
                        'points'      => 10,
                    ],
                ],
            ],
        ];

        foreach ($tests as $testData) {
            $questions = $testData['questions'];
            unset($testData['questions']);

            $test = OrientationTest::firstOrCreate(['title' => $testData['title']]);
            $test->update($testData);

            $test->questions()->delete();
            foreach ($questions as $questionData) {
                TestQuestion::create(array_merge($questionData, ['test_id' => $test->id]));
            }
        }

        $this->command->info(
            '✅ OrientationTestSeeder: ' . OrientationTest::count() . ' tests, ' .
            \App\Models\TestQuestion::count() . ' questions seeded.'
        );
    }
}
